= Asciidoctorj performance tester
:icons: font
ifdef::env-github[]
:important-caption: :exclamation:
endif::[]

Project to reproduce performance regression in Asciidoctorj when using concurrent-ruby 1.1.8 vs 1.1.7.
Overall there's a huge increase in time when using the newer version.
This does not seem to happen when using normal Ruby and some quick analysis points to `Ruby.evalScriptlet` method.

For details: https://github.com/asciidoctor/asciidoctorj/issues/1032.

To reproduce alternate between versions of Asciidoctorj (which bundles the gems) in `converter/build.gradle` 
and run `runner-java.sh` to obtain results.

IMPORTANT: Number format (using , or .) in output files may change depending on machine configuration.

== Running Asciidoctorj over jRuby

Just run script in root

 $ ./runner-java.sh

This will generate 2 output files

* `${TIMESTAMP}_java_convert_times.txt`: times for AsciidoctorJ conversion times in seconds.
* `${TIMESTAMP}_java_total_jvm_times.txt`: total time, including jvm initialization + conversion, in seconds. 

== Running Asciidoctor over Ruby

NOTE: For comparison, Ruby conversions test but not relevant for the Java timing issues.

Just run script in root

 $ ./runner-ruby.sh

This will generate an output file (`${TIMESTAMP}_ruby_times.txt`) with a row for each timing.
